### ISSUE TITLE
<SUBSCRIPT> error in GetRelationships

### ISSUE THREAD

**Issue by sduncan01** [psteiwer/DeepSeeButtons#16]
A user recently reported that DeepSeeButtons failed with a <SUBSCRIPT> error. Output from Terminal is below, with namespace/cube names changed. Based on the error message, I believe the routine failed in GetRelationships. An HTML output file was still created but was missing some closing tags in the "Cubes in <Namespace>" section.

%SYS>D ^DeepSeeButtons
DeepSee Diagnostic Report Evidence Logging Tool
This reporting tool provides the information required for InterSystems Technical Support to analyze DeepSee issues.
Type namespace [%SYS] TESTNSPACE
Give cube name for detailed cube info or press enter to continue: TESTCUBE
Give cube name for detailed cube info or press enter to continue:
Include cconsole.log, Query Log, and DeepSee Logs? [Y]
Continue? [Y]
Collecting information, please do not interrupt this process.
Getting cube informationexc=<OBJECT REFERENCE>[139@%Exception.SystemException]
+----------------- general information ---------------
|     oref value: 139
|     class name: %Exception.SystemException
| reference count: 2
+----------------- attribute values ------------------
|              Code = 16 <Set>
|              Data = "dimlist() Subscript 1 is """"" <Set>
|    InnerException = "" <Set>
|          Location = "DiskSpace+64^DeepSeeButtons" <Set>
|              Name = "<SUBSCRIPT>" <Set>
|            iStack = $lb("^DiskSpace+64^DeepSeeButtons^1","d^LogCubeSection+54^DeepSeeButtons^4","d^LogSections+11^DeepSeeButtons^1","e^LaunchLogs+15^DeepSeeButtons^1","d^StartDialog+19^DeepSeeButtons^1","d^^^0")
+-----------------------------------------------------
Getting Query Log, DeepSee logs, and cconsole.log

**Comment by psteiwer** [comment]
I was not able to reproduce this, but hopefully this change will protect against subscript errors
